export const metadata = {
  title: "View details blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="py-5">{children}</div>;
}
